image: thomasweise/docker-texlive-full

stages:
  - build
  - package

parallel: 3

build_cv1:
  stage: build
  script:
    - latexmk -pdflatex=lualatex -pdf CV.tex

build_cv2:
  stage: build
  script:
    - latexmk -pdflatex=lualatex -pdf CV2.tex

build_coverletter:
  stage: build
  script:
    - latexmk -pdflatex=lualatex -pdf cover_letter.tex

package:
  stage: package
  needs:
    - build
  rules:
    - when: manual
  script:
    - tar -czvf HosseinBehehti.tar.gz CV.pdf CV2.pdf cover_letter.pdf
  artifacts:
    expire_in: 4 week
