stages:
  - build

build_cv:
  stage: build
  image: texlive/texlive
  script:
    - latexmk -pdflatex=lualatex -pdf CV.tex
  artifacts:
    paths:
      - CV.pdf
    expire_in: 4 week

build_coverletter:
  stage: build
  image: texlive/texlive
  script:
    - latexmk -pdflatex=lualatex -pdf cover_letter.tex
  artifacts:
    paths:
      - cover_letter.pdf
    expire_in: 4 week
