name: LaTeX CI
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build LaTeX document
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ./
          key: ${{ runner.os }}-latex-cache
      - run: |
          echo "Compiling LaTeX document..."
          pdflatex CV.tex
      - run: |
          echo "PDF file is saved at ./CV.pdf"